const assert = require('assert');

const {
  classifyCompany,
  classifyDevice,
  classifyEmployee,
  classifyEvidenceRow,
  classifyIdentityMapping,
  classifySite,
  isProductManagedEmployee,
  isProductReadyDevice
} = require('../../services/dataHygieneClassification');

function run() {
  assert.strictEqual(classifyCompany({ company_id: 'DEFAULT' }), 'product_current');
  assert.strictEqual(classifyCompany({ company_id: 'auth-v1-abc' }), 'auth_validation');

  assert.strictEqual(classifySite({
    site_key: 'default-site',
    site_name: 'Default Site',
    status: 'active',
    metadata: { product_default_site: true }
  }), 'product_current');
  assert.strictEqual(classifySite({
    site_key: 'lease-site-abc123',
    site_name: 'Lease Site',
    status: 'active',
    metadata: { run_id: 'abc123' }
  }), 'test_fixture');

  const k80 = {
    device_uid: 'zkteco:sn:BIND-QUEUE-c26a7486',
    provider: 'zkteco',
    device_name: 'ZKTeco K80 Pro',
    managed_status: 'managed',
    metadata: { connection: { host: '192.168.22.201', port: 4370 } }
  };
  assert.strictEqual(classifyDevice(k80), 'product_current');
  assert.strictEqual(isProductReadyDevice(k80), true);
  assert.strictEqual(classifyDevice({ device_uid: 'zkteco:sn:EVT-abc', device_name: 'Event Device abc' }), 'autogenerated_test');

  const productEmployee = {
    person_id: 'emp_1',
    employee_code: 'E001',
    full_name: 'Product Employee',
    metadata: { product_managed: true, source: 'product_ui' }
  };
  assert.strictEqual(isProductManagedEmployee(productEmployee), true);
  assert.strictEqual(classifyEmployee(productEmployee), 'product_current');
  assert.strictEqual(classifyEmployee({ person_id: '1001_run_vendcsv', metadata: {} }), 'vendor_import_test');
  assert.strictEqual(classifyEmployee({ person_id: 'autoreg_person_123', full_name: 'AutoReg Test', metadata: {} }), 'autogenerated_test');
  assert.strictEqual(classifyEmployee({ person_id: 'real_unknown', full_name: 'Unknown Person', metadata: {} }), 'unknown_keep');

  assert.strictEqual(classifyIdentityMapping(
    { provider: 'zkteco', identifier_type: 'device_user_id', identifier_value: '3', person_id: 'emp_1', metadata: {} },
    productEmployee
  ), 'product_current');
  assert.strictEqual(classifyIdentityMapping({ provider: 'anviz', identifier_value: '1001_x_vendanviz', person_id: '1001_x_vendanviz' }), 'vendor_import_test');

  assert.strictEqual(classifyEvidenceRow({ device_uid: 'zkteco:sn:BIND-QUEUE-c26a7486' }), 'protocol_evidence');
  assert.strictEqual(classifyEvidenceRow({ device_uid: 'DEV-BULK-A' }), 'test_fixture');

  console.log('PASS: data hygiene classification');
}

run();
