-- Core schema baseline to ensure rebuild consistency

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.device_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id TEXT NOT NULL DEFAULT 'DEFAULT',
    person_id TEXT NOT NULL,
    event_time_utc TIMESTAMPTZ NOT NULL,
    direction TEXT NOT NULL,
    vendor TEXT,
    device_uid TEXT NOT NULL,
    raw_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS device_events_dedup_company_uk
    ON public.device_events (company_id, person_id, event_time_utc, direction, device_uid);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'device_events_device_uid_nonempty'
  ) THEN
    ALTER TABLE public.device_events
      ADD CONSTRAINT device_events_device_uid_nonempty
      CHECK (length(device_uid) > 0) NOT VALID;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.attendance_days (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id TEXT NOT NULL DEFAULT 'DEFAULT',
    person_id TEXT NOT NULL,
    work_date DATE NOT NULL,
    rule_set_id UUID,
    status TEXT,
    metrics JSONB,
    flags JSONB,
    audit JSONB,
    signature TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS attendance_days_company_person_date_uk
    ON public.attendance_days (company_id, person_id, work_date);

CREATE TABLE IF NOT EXISTS public.employee_leaves (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id TEXT NOT NULL DEFAULT 'DEFAULT',
    person_id TEXT NOT NULL,
    leave_type TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Optional metadata/config tables (baseline only)
CREATE TABLE IF NOT EXISTS public.company_config (
    company_id TEXT PRIMARY KEY,
    timezone TEXT NOT NULL DEFAULT 'Africa/Tunis'
);

CREATE TABLE IF NOT EXISTS public.company_working_days (
    company_id TEXT NOT NULL,
    day_of_week INT NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    is_working_day BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY (company_id, day_of_week)
);
