function text(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function lower(value) {
  return text(value).toLowerCase();
}

function object(value) {
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

function metadata(row) {
  return object(row && row.metadata);
}

function connection(row) {
  const meta = metadata(row);
  const nested = object(meta.connection || meta.network);
  return {
    host: text(row && (row.host || row.ip)) || text(nested.host || nested.ip || meta.host || meta.ip),
    port: Number((row && row.port) || nested.port || meta.port || 0)
  };
}

const TEST_NAME_PATTERN = /(^|[:_\-\s])(test|candidate|incomplete|conflict|readiness|demo|tmp)([:_\-\s]|$)|lease-site-|hq-[0-9a-f]{8}|contract_test/i;
const GENERATED_DEVICE_PATTERN = /zkteco:sn:(mon|rt|evt|b1-conflict|readiness)-|^dev-bulk-|^test-device-|^demo-device-/i;
const GENERATED_PERSON_PATTERN = /1001_|1002_|autoreg|dedup|evt_person|norm_|preview|registry|policy_vendor|vendor|vendcsv|vendanviz|test/i;
const VENDOR_IMPORT_PATTERN = /vendcsv|vendanviz|bioenable|hfsecurity|mantra|integrated_biometrics|normtest|generic_punchlog/i;

function isProductCurrentCompany(row) {
  return text(row && row.company_id) === 'DEFAULT';
}

function isProductCurrentSite(row) {
  const meta = metadata(row);
  const key = lower(row && row.site_key);
  const name = lower(row && row.site_name);
  return lower(row && row.status) === 'active'
    && (meta.product_default_site === true || key === 'default-site' || name === 'default site')
    && !TEST_NAME_PATTERN.test(`${key} ${name} ${text(meta.purpose)}`);
}

function isProductReadyDevice(row) {
  const c = connection(row);
  const label = `${text(row && row.device_uid)} ${text(row && row.device_name)}`;
  return lower(row && row.managed_status) === 'managed'
    && Boolean(text(row && row.provider))
    && Boolean(c.host)
    && Boolean(c.port)
    && !GENERATED_DEVICE_PATTERN.test(label)
    && !TEST_NAME_PATTERN.test(label);
}

function isProductManagedEmployee(row) {
  return metadata(row).product_managed === true;
}

function isProductIdentityMapping(row, employee) {
  return Boolean(employee && isProductManagedEmployee(employee))
    || metadata(row).source === 'employee_management_v1';
}

function classifyCompany(row) {
  const id = text(row && row.company_id);
  if (id === 'DEFAULT') return 'product_current';
  if (/^auth-v1-|^authv1/i.test(id)) return 'auth_validation';
  if (/^contract-|^demo$/i.test(id)) return 'test_fixture';
  return 'unknown_keep';
}

function classifySite(row) {
  const label = `${text(row && row.site_key)} ${text(row && row.site_name)} ${text(metadata(row).purpose)}`;
  if (isProductCurrentSite(row)) return 'product_current';
  if (/lease-site-|hq-[0-9a-f]{8}|contract_test/i.test(label)) return 'test_fixture';
  return 'unknown_keep';
}

function classifyDevice(row) {
  const label = `${text(row && row.device_uid)} ${text(row && row.device_name)} ${text(row && row.source)} ${text(row && row.lifecycle_scope)}`;
  if (text(row && row.device_uid) === 'zkteco:sn:BIND-QUEUE-c26a7486') return 'product_current';
  if (/zkteco:sn:(mon|rt|evt|b1-conflict|readiness)-/i.test(label)) return 'autogenerated_test';
  if (/^dev-bulk-|^test-device-|^demo-device-|test|candidate|conflict|demo/i.test(label)) return 'test_fixture';
  if (isProductReadyDevice(row)) return 'unknown_keep';
  return 'unknown_keep';
}

function classifyEmployee(row) {
  const label = `${text(row && row.person_id)} ${text(row && row.employee_code)} ${text(row && row.full_name)}`;
  if (isProductManagedEmployee(row)) return 'product_current';
  if (VENDOR_IMPORT_PATTERN.test(label)) return 'vendor_import_test';
  if (/autoreg|dedup|evt_person|norm_|preview|registry|policy_vendor/i.test(label)) return 'autogenerated_test';
  if (GENERATED_PERSON_PATTERN.test(label)) return 'legacy_test';
  return 'unknown_keep';
}

function classifyIdentityMapping(row, employee) {
  const label = `${text(row && row.provider)} ${text(row && row.identifier_type)} ${text(row && row.identifier_value)} ${text(row && row.person_id)}`;
  if (isProductIdentityMapping(row, employee)) return 'product_current';
  if (VENDOR_IMPORT_PATTERN.test(label)) return 'vendor_import_test';
  if (GENERATED_PERSON_PATTERN.test(label)) return 'legacy_test';
  return 'unknown_keep';
}

function classifyEvidenceRow(row) {
  const deviceUid = text(row && row.device_uid);
  if (deviceUid === 'zkteco:sn:BIND-QUEUE-c26a7486') return 'protocol_evidence';
  if (/dev-bulk-|test-device|demo-device|csv-commit|anviz:|hfsecurity:|bioenable:|mantra:|integrated_biometrics:/i.test(deviceUid)) {
    return 'test_fixture';
  }
  return 'unknown_keep';
}

function classifyAgentCommand(row) {
  const type = text(row && row.command_type);
  if (/PULL_DEVICE_EVENTS|START_DEVICE_MONITORING|STOP_DEVICE_MONITORING|REFRESH_DEVICE_PATH_PULL_CAPABILITY/i.test(type)) {
    return 'product_validation';
  }
  if (/ENROLLMENT|SCAN_SUBNET|VALIDATE_DEVICE_CANDIDATE|pull-events/i.test(type)) return 'protocol_evidence';
  return 'unknown_keep';
}

module.exports = {
  classifyAgentCommand,
  classifyCompany,
  classifyDevice,
  classifyEmployee,
  classifyEvidenceRow,
  classifyIdentityMapping,
  classifySite,
  isProductCurrentSite,
  isProductIdentityMapping,
  isProductManagedEmployee,
  isProductReadyDevice
};
